# Un protocolo para informar sobre modelos discreto de estructura de población



### "A standard protocol to report discrete stage-structured demographic information" {.unnumbered}

#### Samuel J. L. Gascoigne$^1$ | Simon Rolph$^2$ | Daisy Sankey$^1$ | Nagalakshmi Nidadavolu$^1$ | Adrian S. Stell Pičman$^1$$^,$$^3$ | Christina M. Hernández$^4$ | Matthew E. R. Philpott$^1$ | Aiyla Salam$^1$ | Connor Bernard$^1$ | Erola Fenollosa$^1$ | Young Jun Lee$^1$ | Jessica McLean$^1$ | Shathuki Hetti Achchige Perera$^1$ | Oliver G. Spacey$^1$ | Maja Kajin$^1$$^,$$^3$ | Anna C. Vinton$^1$ | C. Ruth Archer$^5$ | Jean H. Burns$^6$ | Danielle L. Buss$^7$$^,$$^8$ | Hal Caswell$^9$ | Judy P. Che-Castaldo<sup>10</sup> | Dylan Z. Childs<sup>2</sup> | Pol Capdevila<sup>11</sup> | Aldo Compagnoni<sup>1,12,13</sup> | Elizabeth Crone<sup>14</sup> | Thomas H. G. Ezard<sup>15</sup> | Dave Hodgson<sup>8</sup> | Tiffany M. Knight<sup>12,13,16</sup> | Owen R. Jones<sup>17</sup> | Eelke Jongejans<sup>18,19</sup> | Jenni McDonald<sup>20,21</sup> | Brigitte Tenhumberg<sup>22</sup> | Chelsea C. Thomas<sup>23</sup> | Andrew J. Tyre<sup>2,4,25</sup> | Satu Ramula<sup>26</sup> | Iain Stott<sup>27</sup> | Raymond L. Tremblay<sup>28,29,30</sup> | Phil Wilson<sup>8</sup> | James W. Vaupel<sup>31,‡</sup> | Roberto Salguero-Gómez<sup>1,32,33</sup> {.unnumbered}

 <sup>1</sup>Department of Biology, University of Oxford, Oxford, UK; <sup>2</sup>Department of Animal & Plant Sciences, University of Sheffield, Sheffield, UK; <sup>3</sup>Department of Biology, University of Ljubljana, Ljubljana, Slovenia; <sup>4</sup>Department of Ecology and Evolutionary Biology, Cornell University, Ithaca, New York, USA; <sup>5</sup>Institute of Evolutionary Ecology and Conservation Genomics, University of Ulm, Ulm, Germany; <sup>6</sup>Department of Biology, Case Western Reserve University, Cleveland, Ohio, USA; <sup>7</sup>Department of Archaeology, University of Cambridge, Cambridge, UK; <sup>8</sup>College of Life and Environmental Sciences, University of Exeter, Penryn, UK; <sup>9</sup>Institute for Biodiversity and Ecosystem Dynamics, University of Amsterdam, Amsterdam, The Netherlands; <sup>10</sup>Branch of Species Status Assessment
Science Support, U.S. Fish and Wildlife Service, Washington, DC, USA; <sup>11</sup>School of Biological Sciences, University of Bristol, Bristol, UK; <sup>12</sup>Institute of Biology, Martin Luther University Halle-Wittenburg,
Halle (Saale), Germany; <sup>13</sup>German Centre for Integrative Biodiversity Research (iDiv) Halle-Jena-Leipzig, Leipzig, Germany; <sup>14</sup>Department of Biology, Tufts University, Medford, Massachusetts, USA; <sup>15</sup>School of Ocean and Earth Science, University of Southampton, Southampton, UK; <sup>16</sup>Department of Community Ecology, Helmholtz Centre for Environmental Research-UFZ, Halle (Saale), Germany; <sup>17</sup>Department of Biology, University of Southern Denmark, Odense, Denmark; <sup>18</sup>Animal Ecology and Physiology, Radboud University, Nijmegen, The Netherlands; <sup>19</sup>NIOO-KNAW, Animal Ecology, Wageningen, The Netherlands; <sup>20</sup>Veterinary Department, Cats Protection, National Cat Centre, Haywards Heath, UK; <sup>21</sup>Bristol Veterinary School, University of Bristol, Bristol, UK; <sup>22</sup>School of Biological Sciences and Department of Mathematics, University of Nebraska, Lincoln, Nebraska, USA; <sup>23</sup>Alexander Center for Applied Population Biology, Conservation & Science Department, Chicago, Illinois, USA; <sup>24</sup>School of Natural Resources, University of Nebraska-Lincoln, Lincoln, Nebraska, USA; <sup>25</sup>Global Resistance Management Team, Bayer U.S. –Crop Science, Chesterfield, Missouri, USA; <sup>26</sup>Department of Biology, University of Turku, Turku, Finland; <sup>27</sup>School of Life Sciences, University of Lincoln, Lincoln, UK; <sup>28</sup>Department of Biology, University of Puerto Rico, San Juan, Puerto Rico, USA; <sup>29</sup>Center for Applied Tropical Ecology and Conservation, University of Puerto Rico, San Juan, Puerto Rico, USA; <sup>30</sup>Department of Biology, University of Puerto Rico-Humacao, Puerto Rico, USA; <sup>31</sup>Interdisciplinary Centre on Population Dynamics, University of Southern Denmark, Odense, Denmark; <sup>32</sup>Centre for Biodiversity and Conservation Science, University of Queensland, St Lucia, Queensland, Australia y <sup>33</sup>Evolutionary Demography Laboratory, Max Planck Institute for Demographic Research, Rostock, Germany

***
### Persona de contacto {.unnumbered}

Samuel J. L. Gascoigne
Email: samuel.gascoigne@pmb.ox.ac.uk

Roberto Salguero-Gómez
Email: rob.salguero@biology.ox.ac.uk



Por: Traducido por Anne DAMON, RLT....

***
Nota: Cualquier conflicto entre el texto en ingles y español, siempre se deberia usar el texto en ingles como guia. 

***

#### Cuando cita el articlo use la siguiente información, [@gascoigne2023standard] {.unnumbered}


### Abstract {.unnumbered}

1. Los métodos demográficos que se basan en etapas, como los Modelos Matriciales Poblacionales (MPM, por sus siglas en inglés), son herramientas poderosas que se utilizan para abordar una amplia gama de preguntas fundamentales en ecología, biología evolutiva y ciencias de la conservación. Por ello, ahora existen MPM para más de 3,000 especies en todo el mundo. Estos datos se están digitalizando como un proceso continuo y se publican periódicamente en dos grandes repositorios en línea de acceso abierto: la base de datos de matrices vegetales de COMPADRE y la base de datos de matrices animales de COMADRE. Sin embargo, durante la última década, el análisis y la curación de los datos de COMPADRE y COMADRE, y la investigación comparativa posterior, han revelado una variación pronunciada en la forma en que se parametrizan y reportan los MPM.
2. Aquí resumimos los problemas actuales relacionados con la parametrización y difusión de los MPM, los que surgen con más frecuencia, y describimos cómo afectan la construcción, el análisis y la interpretación de los MPM. Para cuantificar la variación en cómo se difundan los MPM, presentamos los resultados de una encuesta que buscaba identificar aspectos clave de los MPM que con frecuencia no se presentan en los manuscritos. Luego evaluamos las bases de datos de COMPADRE y COMADRE para cuantificar con qué frecuencia se omiten piezas clave de información en los manuscritos donde manejan los MPM. 
3. Más del 80 % de los y las investigadores entrevistados (n = 60) comentaron de las ventajas de adoptar metodologías más estandarizadas para difundir y compartir los MPM. Además, más del 85% de los 300 MPM evaluados por COMPADRE y COMADRE omitieron uno o más de los elementos clave para su correcta interpretación. Basado en estos resultados, identificamos los principales problemas que pueden surgir a partir de la construcción y difusión de los MPM y brindamos sugerencias para mejorar la claridad y la reproducibilidad y así contribuir a la investigación futura utilizando MPM y los metadatos requeridos. Para fortalecer la reproducibilidad y capacitar a los investigadores para aprovechar al máximo sus datos demográficos, presentamos un protocolo estandarizado para presentar los MPM en las publicaciones. Este estándar está vinculado con el contenido de www.compa dre-db.org, para que los autores que deseen archivar sus MPM puedan hacerlo antes de someter sus publicaciones, siguiendo ejemplos de otros repositorios de acceso abierto como DRYAD, Figshare y Zenodo.
4. La combinación y estandarización de MPM parametrizados provenientes de poblaciones de todo el mundo, y de todo el árbol de la vida de los organismos, abre poderosas oportunidades de investigación en biología evolutiva, ecología y conservación. Sin embargo, enfatizamos que este potencial solo se logrará mediante la adopción de métodos estandarizados para garantizar la reproducibilidad. 
PALABRAS CLAVE 
demografía comparativa, modelos matriciales de población, acceso abierto, reproducibilidad

### 1 | INTRODUCCION  {.unnumbered}

La ecología de poblaciones ha llegado a la mayoría de edad. El desarrollo de teorías, enfoques experimentales y metodologías estadísticas han dado como resultado la publicación de información demográfica para una muestra cada vez más representativa de la biodiversidad mundial (De Magalhᾶes & Costa, 2009; Levin et al., 2022; Salguero-Gómez et al., 2015, 2016). Estos datos abarcan el árbol taxonómico desde los microbios (Jouvet et al., 2018) hasta macrovertebrados (Fujiwara & Caswell, 2001), y cubren prácticamente todos los continentes y biomas, aunque con importantes sesgos taxonómicos (Conde et al., 2019; Römer et al., 2021). El potencial de esta cantidad de información impresionante y en rápido aumento está comenzando a realizarse. De hecho, mediante la combinación de estos modelos demográficos, los investigadores han identificado características funcionales que explican la variación en las estrategias de la historia de vida de las plantas (Adler et al., 2014; ver también Bernard et al., 2023), características a corto plazo (transitorias) que impulsan la evolución demográfica, la dinámica de las poblaciones de plantas en ambientes variables (McDonald et al., 2016), y las formas en que las estrategias de historia de vida permiten que las especies persistan en un entorno de clima cambiante (Jelbert et al., 2019; Paniw et al., 2019). 

Una de las herramientas más utilizadas para describir y analizar las complejas historias de vida de las especies es la de los modelos de población matricial (MPM). Brevemente, en un MPM, los individuos de una población se clasifican por etapas discretas y/o edades (st/edad en adelante) de acuerdo con algunos criterios biológicos (Caswell, 2001, p. 31) o estadísticos/de muestreo (Salguero-Gómez & Plotkin, 2010). Estos individuos son seguidos en pasos de tiempo discretos, típicamente ajustados por el tiempo de generación de cada especie. De hecho, los pasos de tiempo pueden variar de 12 a 24 h, como en los gusanos nematodos Caenorhabditis elegans y pulgones Myzus periscae (Bruijning et al., 2019; Li et al., 2014), a períodos mensuales/anuales en mamíferos y plantas (Coulson et al., 2001; Ferreira et al., 2016), y hasta los 50 años en los “red woods” de crecimiento lento (Namkoong & Roberds, 1974). A partir de estos datos, los investigadores estiman pérdidas por mortalidad, probabilidades de transición entre estadios/edades y su per cápita contribuciones a/sexuales a través de la reproducción (Nordstrom et al., 2021; Omeyer et al., 2021). 

A partir de un solo MPM se puede calcular un amplio repertorio de resultados biológicamente significativos. Estos resultados incluyen indicadores estimados del desempeño y la viabilidad de las poblaciones, como tasas de crecimiento demográfico deterministas (γ) o estocásticas (γs) (Doak et al., 2005), riesgo de cuasi-extinción (Davis, 2022), respuesta de la población a perturbaciones de las tasas vitales subyacentes, como la supervivencia o la reproducción (Caswell, 2001, p. 206), dinámica transitoria (Capdevila et al., 2020, Ezard et al., 2010; Stott et al., 2011) y rasgos de historia de vida, como tasas de senescencia (Baudisch et al., 2013), grado de iteroparidad (Salguero-Gómez et al., 2017) y edad de madurez (Caswell, 2001, p. 124). Esta gran cantidad de inferencias demográficas destaca el por qué han sido tan importantes los MPM para el desarrollo de la demografía y la teoría de la historia de vida (Franco & Silvertown, 1996; Pfister, 1998; Sæther et al., 2013; Tuljapurkar, 1989). 

Los MPM para plantas y animales han sido archivados, corregidos, complementados con información adicional (p. ej., coordenadas GPS, estado de conservación de la UICN) y publicados en medios de acceso abierto en la Base de Datos de Matrices Vegetales de COMPADRE (Salguero-Gómez et al., 2015) y el Base de Datos de Matrices Animales COMADRE (Salguero-Gómez et al., 2016). En la publicación más reciente, COMPADRE v. 6.22.5 [COMADRE v. 4.21.8] se presentan datos de 8851 [3317] MPM de 760 [415] especies distintas, trabajadas en 643 [395] estudios. Al momento de redactar este informe, otras 1307 especies están pendientes de digitalización en la red COMPADRE, con una tasa aproximado de 4.5 nuevos trabajos que contienen MPM siendo analizados, digitalizados y pasados por un proceso de control de calidad cada semana (S. Gascoigne, obs. pers.). Sin embargo, uno de los desafíos del proceso de digitalización es la enorme variación en la forma en que se recopilan, presentan y utilizan los datos para parametrizar los MPM. 
La estandarización de datos mejora la capacidad de replicación y facilita el intercambio de datos entre disciplinas de investigación (Reichman et al., 2011). Por lo tanto, la estandarización de los datos, y los metadatos detallados asociados, es clave para que la investigación se replique, valide y discuta abiertamente para que la ciencia avance (Powers & Hampton, 2019; Reichman et al., 2011; Salguero-Gómez et al., 2021). Ejemplos de estos estándares incluyen, informar del tamaño de la muestra y de la varianza de las estimaciones, además de detallar la lista completa de fuentes originales de datos (Gerstner et al., 2017). En este contexto, los estándares se pueden utilizar como elementos de una lista de requisitos para mejorar la calidad y la reproducibilidad de las publicaciones y el proceso de arbitraje por pares (Reichman et al., 2011). Este proceso de estandarización hará posible ampliar el alcance del análisis, mediante la inclusión de los meta-análisis (Gurevitch et al., 2018) y los análisis comparativos filogenéticos (Healy et al., 2019; Salguero-Gómez et al., 2017), que ofrecen oportunidades valiosas para examinar patrones generales e identificar lagunas en el conocimiento, y en ambos casos también dependen de datos que conforman a determinadas normas.

Los MPM se están adaptando, ampliando y aplicando más allá de su contexto original especie-específica en la demografía comparativa. Sin embargo, no todos los MPM se construyen y se reporten de la misma manera. La presentación actual de las MPM en COMPADRE y COMADRE nos podría dar la falsa impresión de que todos los MPM se conformen a un formato homogéneo predeterminado, y esto a pesar de las diferencias en cómo y por qué fueron concebidos los MPM (Caswell, 2001). Esta impresión pudo haber surgido por el extenso proceso de verificación que realiza el equipo de digitalización de COMADRE y COMPADRE atrás de las escenas (p. ej., validación de los resultados del modelo, correspondencia con el autor para obtener información adicional). Si bien la verificación es un aspecto inevitable de la curación de bases de datos, la mayor parte de nuestros esfuerzos se dedica a comunicarnos con los autores en lugar de la digitalización de datos. Nuestro objetivo aquí es (i) presentar el estándar actual de comunicación de los MPM en la literatura, (ii) identificar problemas comunes en la comunicación de los MPM y sus impactos, (iii) sugerir formas de apoyar la comunicación clara de datos y metadatos de los MPM, (iv) destacar las ventajas para los autores y la comunidad científica en general y (v) introducir un método estándar para compartir datos y metadatos de los MPM.

### 2 | COMUNICACIÓN MPM: ESTADO DEL ARTE {.unnumbered}

Para presentar las prácticas actuales en la comunicación de datos y metadatos de los MPM, con el objetivo final de evaluar la necesidad de estandarizar informes de datos y metadatos, realizamos una encuesta de investigadores y examinamos un subconjunto de publicaciones que se han utilizado para generar MPMs y que han sido almacenados en COMPADRE y COMADRE. 

### 2.1 | Una encuesta sobre comunicación matricial {.unnumbered}

Entrevistamos especialistas de ecología de poblaciones, a quienes identificamos por haber publicado artículos revisados por pares que incluyen MPM, con respecto a nuestra capacidad actual para comunicar datos y metadatos de los MPM con fines de reproducibilidad. Específicamente, preguntamos qué tan bien las publicaciones revisadas por pares transmiten los atributos de los MPM necesarios para asegurar la reproducibilidad. Además, preguntamos si los investigadores pensaban que un método estandarizado de comunicación matricial es "necesario para la comunicación coherente de los MPM en la literatura" (la lista completa de 11 preguntas se puede encontrar en Información de apoyo). La encuesta se distribuyó mediante Google Forms. Identificamos 1390 participantes potenciales bajo el criterio de ser el autor principal y/o de correspondencia de una publicación que contiene al menos un MPM. Más del 50% de las direcciones de correo electrónico correspondientes estaban desactualizadas y no hubo seguimiento. De los aproximadamente 650 investigadores restantes que fueron contactados, 60 participantes completaron la encuesta. Como era de esperar, los investigadores comentaron de una gran heterogeneidad en los componentes incluidos en la comunicación de los MPM (Figura 1). Los atributos mejor comunicados según estos participantes de la encuesta son los nombres de los rasgos (es decir, el fenotipo mediante el cual se estructuró el MPM: etapa/edad/tamaño clases), la duración del censo e intervalo de proyección, mientras que los atributos peor comunicados son los gráficos del ciclo de vida, fórmulas que definen las tasas vitales y los vectores de población (es decir, número/frecuencia de individuos en cada etapa/edad). Es importante destacar que el 83% de los participantes de la encuesta acordaron que la disciplina si necesita un método estandarizado para la comunicación de los MPM.

### 2.2 | Una muestra de publicaciones en COMPADRE y COMADRE {.unnumbered}

Para cuantificar qué tan bien se comunican los datos y metadatos de los MPM en publicaciones revisadas por pares, seleccionamos al azar 300 artículos entre los que contenían MPM ya digitalizados en COMPADRE y COMADRE, quedando con 150 artículos en cada caso. Entre los diferentes atributos clave de los MPM que examinamos, hubo una variación considerable en la confiabilidad con la que los autores proporcionaron los datos y metadatos necesarios para digitalizar, archivar y realizar análisis comparativos (Figura 2). Por ejemplo, la ubicación genérica de la población examinada (i.e. provincia/ciudad/monumento; COMPADRE: 95.1%, COMADRE: 86.2% de los trabajos lo reportaron), el MPM totalmente parametrizado (93.3%, 88.9%) y la fecha del censo (89.6 %, 77.7 %) se indicaron explícitamente con frecuencia en los artículos, mientras que la latitud y longitud de la población examinada (52.4 %, 39.9 %), su diagrama de ciclo de vida (44.5 %, 40.1 %) y el vector de población (es decir, st/ la distribución por edades de los individuos en el momento t) (33.2 %, 32.6 %) se indicaron con menor frecuencia. Curiosamente, los estudios de plantas que utilizan MPM (COMPADRE) contienen en general datos y metadatos más completos y claros que los estudios de animales (COMADRE; Figura 2). Utilizamos esta información para categorizar la calidad de cada uno de los 300 artículos examinados en términos de su reproducibilidad, definida como la inclusión de los componentes necesarios para la  comunicación de los MPM (Figura 3). La distribución de estos componentes de comunicación entre los reinos es similar. Fundamentalmente, solo el 13.9 % de los artículos en COMADRE y el 15.8 % de los artículos en COMPADRE contienen toda la información necesaria para realizar análisis comparativos y proyecciones precisas (Figura 3). Por lo tanto, en aproximadamente el 85 % de los artículos se requiere enviar un correo electrónico a los autores para solicitar la información faltante.

### 3 | PROBLEMAS COMUNES CON LA CONSTRUCCIÓN DE MATRICES {.unnumbered}

Aquí, identificamos problemas clave en la parametrización de los MPM para ilustrar el impacto de la metodología en el potencial de extrapolación demográfica. Para hacerlo, nos basamos en los hallazgos de la sección anterior y nuestra experiencia con la curación de COMPADRE y COMADRE. Señalamos las siguientes cuestiones por dos razones: (i) para guiar los demógrafos en cómo identificar estas cuestiones en la literatura y (ii) para evitar que persistan estos problemas en futuras publicaciones. Señalamos que un lista completa fue difundido recientemente por Kendall et al. (2019, véase también Che-Castaldo et al., 2020). Aquí, ampliamos estos documentos anteriores indicando los pasos necesarios para que los investigadores puedan evitar/mitigar estos problemas en su propia investigación. Un resumen de estos problemas, desde la ocurrencia hasta impacto, se detalla en la Figura S1.
3.1 | Tipo de censo, temporalidad y frecuencia
 Los MPM son modelos demográficos de tiempos medidos, parametrizados mediante el seguimiento de individuos tras los muestreos o censos. Por lo tanto, el tipo (p. ej., longitudinal, transversal), el momento y la frecuencia de los muestreos o censos deben planificarse cuidadosamente. Estos criterios son particularmente importantes ya que el tipo de censo afecta directamente a la construcción de la matriz, y el momento y la frecuencia del censo pueden influir involuntariamente en los resultados demográficos (Emery & Gross, 2005). 
 
Por lo general, los MPM se manejan de dos formas con respecto a la medición de la reproducción entre censos: nacimiento-flujo o nacimiento-pulso (ver Caswell, 2001, p. 22). La distinción se basa en si la reproducción se produce de forma continua (es decir, nacimiento-flujo) o en una estrecha ventana temporal (nacimiento-pulso). Los MPM de nacimiento-pulso a su vez se subclasifican en censo previo versus pos-reproductivo. Aunque tanto los censos pre-reproductivos como los pos-reproductivos a menudo conducen a un escenario demográfico similar (ver Cooch et al., 2003), su diferencia radica en la relación entre el tiempo del censo de la población y la posición de la estrecha ventana reproductiva. En el primero, las poblaciones son censadas inmediatamente antes de una ventana reproductiva, mientras que los censos post-reproductivos continúan después de una ventana reproductiva. Un censo pre-reproductivo requiere la inclusión de la supervivencia de la descendencia en los elementos de la matriz reproductiva, mientras que un censo post-reproductivo requiere la inclusión de la supervivencia de los padres en los elementos de la matriz reproductiva. A menudo encontramos errores en el acomodo de la descendencia o la supervivencia de los padres en los elementos de la matriz reproductiva (ver también Kendall et al., 2019). Un paso clave en la construcción de la matriz que puede evitar el acomodo incorrecta de la supervivencia sería dibujar el gráfico del ciclo de vida (según Ebert, 1999, p. 61) con respecto al momento del censo (demostrado en Ellner et al., 2016, p. 13), así como también detallar explícitamente el tipo de censo utilizado para parametrizar el MPM. Sin embargo, a veces dibujar el gráfico del ciclo de vida puede que sea inviable o poco informativo. Por ejemplo, el gráfico de un modelo clasificado por edad si tuviera 100 clases de edad sería demasiado grande para dibujarlo y no muy útil; sin embargo, se podría simplificar con una línea discontinua si varias clases adyacentes tienen las mismas tasas demográficas (por ejemplo, Ebert, 1999, p. 2). Los modelos con muchas etapas y transiciones altamente conectadas no son viables para dibujar el gráfico del ciclo de vida (por ejemplo, el gráfico de Calathea ovandensis en Neubert y Caswell (2000)). Pero incluso, en situaciones complejas (por ejemplo, la serie de gráficos estacionales para el pingüino emperador en Jenouvrier et al. (2010)), el gráfico puede ser útil para organizar la estructura del modelo. El tiempo y la frecuencia del censo afectan la construcción del modelo, lo que hace que un MPM construido no sea práctico para la inferencia demográfica si no se considera la historia de vida del organismo examinado. Considere a un investigador que compara los procesos demográficos de las moscas de la fruta y los árboles frutales. El investigador primero nota que hay cuatro etapas discretas en la historia de vida de las moscas de la fruta: tres etapas juveniles que abarcan el desarrollo desde el huevo hasta el estadio y la pupa, y una etapa adulta donde los individuos se dispersan y reproducen. Dado que el desarrollo de huevo a adulto tarda ~10 días en esta especie, el investigador decide realizar el censo cada 10 días tanto para la mosca de la fruta como para los árboles frutales durante un período de 3 meses. Sin embargo, debido a que ni la mortalidad ni la reproducción ocurren en un censo tan corto en la población de árboles frutales, el MPM de árboles frutales resultante, cuando se proyecta hacia adelante, persistirá para siempre, sin aumentar ni disminuir. Este mismo problema ocurriría al revés. Si los intervalos de 5 años se consideraran suficientes para los árboles frutales, las moscas de la fruta medidas individualmente nunca sobrevivirían a lo largo de los períodos de tiempo. Existe una solución a este problema, utilizando modelos de matrices periódicas para incluir períodos mucho más cortos o más largo que otros períodos. Por ejemplo, Hunter y Caswell (2005) analizaron la pardela negra Puffinus griseus incluyendo dos períodos de cosecha de varias semanas de duración y luego un intervalo anual para la especie, con una vida útil de décadas. Smith et al. (2005) y Shyu et al. (2013) utilizaron modelos estacionales periódicos para adaptarse a los ciclos de vida en los que algunas etapas solo están presentes durante una parte del ciclo anual. El enfoque (Caswell, 2001, sección 13.1) es poderoso y general.

### 3.2 | Supervivencia etapa-específica poco realista {.unnumbered}

Los problemas en la parametrización de la supervivencia etapa-específica, si bien son fáciles de diagnosticar, son difíciles de controlar y pueden dar lugar a una variedad de historias de vida no naturales. Las probabilidades de transición y supervivencia están limitadas entre 0 (el evento nunca sucede) y 1 (el evento siempre ocurre). Es evidente que, considerando la etapa-específica supervivencia de un MPM, los elementos no reproductivos sumados en una columna dada del MPM A no deben exceder 1. Cuando lo hace, los individuos en esa etapa tienen una probabilidad poco realista de sobrevivir >100%, lo que resulta en una representación incorrecta de la historia de vida del organismo. Los valores de >1 de supervivencia etapa-específica generalmente surgen debido a errores de redondeo, errores tipográficos, e inclusión de eventos reproductivos a/sexuales no declarados y generalmente se recomienda omitir estos MPM en un análisis comparativo (Jones et al., 2014). Los eventos reproductivos a/sexuales no declarados ocurren cuando un elemento ai,j  en el MPM A combina procesos dependientes de la supervivencia, como el crecimiento/encogimiento, pero también la fertilidad, y que estos no se han informado por separado. De preferencia, los autores identificarían cuidadosamente si varias tasas vitales se confunden con procesos demográficos dependientes de la supervivencia en cada elemento del MPM. Para el demógrafo comparativo que utiliza COMPADRE y COMADRE, recomendamos evitar los modelos MPM donde supervivencia etapa-específica llega a ser >1, y también evitar alterar el modelo para hacer que la supervivencia etapa-específica se fije a un máximo de 1 (p. ej., Buckley et al., 2010). En muchos MPM publicados, algunas de las etapas de la vida tienen un tiempo estimado probabilidad de supervivencia de 1 o un ciclo de vida incompleto, probablemente el resultado de un tamaño de muestra pequeño o algún evento raro a lo largo de la historia de vida del especies. La supervivencia perfecta (es decir, mortalidad = 0) es poco probable y es posible que el valor deba estimarse o imputarse (Johnson et al., 2018). Un método para estimar valores realistas de supervivencia y transición fue propuesto recientemente por Tremblay et al. (2021), utilizando un enfoque bayesiano para estimar los valores de los parámetros utilizando datos previos, además de los datos observados, para obtener los MPM. Una ventaja de este enfoque es que los intervalos de confianza de los parámetros que representan probabilidades (estásis, transición, supervivencia) se obtienen a partir de una distribución beta. La ventaja de usar una distribución de Dirichlet multinomial bayesiana inferida para estimar los valores medios es que los investigadores pueden inferir la varianza y el sesgo de las distribuciones posteriores para informar mejor la construcción de MPM y la interpretación demográfica (p. ej., Tremblay et al., 2009a, 2009b). Por último, dado que el tamaño de la muestra puede ser un factor causante de la supervivencia etapa-específica poco realista, el tamaño de la muestra y la incertidumbre (p. ej., intervalo de confianza, desviación estándar) deben informarse para (1) transmitir la precisión de la supervivencia estimada valor para su audiencia y (2) para la inclusión precisa de los valores de supervivencia en metaanálisis y métodos comparativos.

### 3.3 | Parametrización incorrecta de la fertilidad {.unnumbered}

La fertilidad a menudo presenta un desafío para la construcción de MPM precisos. Este desafío se debe en parte a la ambigüedad del término "fertilidad". El problema surge cuando las contribuciones individuales (per-cápita) de los adultos reproductivos a los nuevos reclutas (por ejemplo, huevos, neonatos, semillas, etc.) no representan los enlaces que contempla el intervalo de proyección completo del estudio. Recuerda que la entrada ai,j en un MPM es el número (esperado) de individuos en etapa i en t + 1 por estadio j individuo en el tiempo t. Si la etapa i es efectivamente un tipo de individuo 'recién nacido', entonces ai,j debe incluir todos los procesos entre tiempo t y tiempo t + 1 (Caswell, 2001, p. 61). Rendimiento reproductiva, a su vez, es un proceso demográfico compuesto del número de descendientes producidos en un evento reproductivo y la supervivencia pertinente que penalizará en cuanto al número de descendientes nuevos que alcanzarán a la siguiente observación. El no tener en cuenta esta descomposición de la tasa vital puede resultar en la introducción de un retraso por un unidad de tiempo (en los términos del caso particular) en el ciclo de vida del organismo, ya que la descendencia recién creada pasaría un intervalo de proyección 'en limbo 'antes de su transiciones hacia delante. El ejemplo más conocido está en el modelo clásico del cardo Dipsacus sylvestris, de Werner y Caswell (1977), en el que las plantas con flores en el momento t, pasaron a tener semillas en el tiempo t + 1, y que éstas solo germinaron para formar plántulas en el tiempo t + 2. Este tema fue discutido y corregido en Caswell (2001). Además, este problema se ha reportado, por ejemplo, en estructuras reproductivas, tales como semillas, que no forman parte de un banco de semillas. Si se presenta este tipo de problema en un MPM, generalmente (Kendall et al., 2019), pero no siempre (Nguyen et al., 2019), se subestima la tasa de crecimiento γ de la población asintótica, y de allí se enfrenta el desafío de estimar la importancia relativa del banco de semillas y la vida útil de estas semillas aun no germinadas. El efecto de parametrizar incorrectamente la fertilidad dentro de la tasa de crecimiento γ es mayor en casos de crecimiento extremo, por ejemplo, en especies invasoras, o, al contrario, disminución extrema, como la que observamos en especies en peligro de extinción crítico (Rueda-Cediel et al., 2018). Este fenómeno también puede causar una sobreestimación de la envoltura transitoria (ver Ezard et al., 2010). Por ello, recomendamos especificar las fórmulas de la tasa vital de fecundidad en conjunto con los MPM asociados e identificar claramente los valores de estas tasas vitales subyacentes (como en el Recuadro 1).  

### 3.4 | Cálculo indirecto de tasas vitales {.unnumbered}

La estimación de las tasas vitales a menudo implica una combinación de medidas directas e indirectas. La medición directa deriva empíricamente las tasas vitales a partir de datos basados en individuos, donde se censan los mismos individuos etiquetados varias veces, como en los estudios de tablas de vida de cohortes, métodos de captura-marcado-recaptura y muchos estudios de cuadrantes de plantas marcadas. Sin embargo, las tasas vitales pueden ser difíciles de observar en especies con altas tasas de reproducción, fenología compleja y/o poblaciones pequeñas (Beissinger & Westphal, 1998). En consecuencia, las estimaciones de reclutamiento a menudo se usan para complementar los MPM desarrollados en condiciones controladas, por ejemplo, en el laboratorio (Jouvet et al., 2018), en un invernadero (Gontijo & Carvalho, 2020), en un zoológico (Clubb et al., 2009) o en un jardín botánico (Jiménez-Valdés et al., 2010). Dado que algunos métodos para el desarrollo de los MPM requieren de un ciclo de vida completo para obtener las métricas clave (por ejemplo, métricas transitorias: Stott et al., 2011), se tiende a utilizar sitios de estudio externos o fuentes de la literatura para parametrizar los componentes que hacen falta para 'cerrar el ciclo' (Omeyer et al., 2021). Sin embargo, hay que tomar en cuenta que las poblaciones cautivas o de alguna forma domesticadas pueden no presentar la misma dinámica poblacional que la población natural (Clubb & Mason, 2003), particularmente en relación a supervivencia (Che-Castaldo et al., 2021) o reproducción (Clubb et al., 2009).

Otro método para estimar indirectamente las tasas vitales consiste en utilizar métodos ex situ para obtener los límites superior e inferior del reclutamiento (u otras tasas vitales) y explorar los espacios ocupados por los parámetros dentro de esos límites. Este enfoque fue introducido por Caswell et al. (1998) en un estudio sobre los efectos de la mortalidad por captura incidental en la marsopa común. Los cronogramas de supervivencia y fertilidad específicos por edad se seleccionaron de otras especies con ciclos de vida similares, se reajustaron para que coincidieran con la longevidad de la marsopa común y se usaron para producir distribuciones de incertidumbre para el crecimiento de la población y los efectos de la captura incidental medida. La información así generada de la distribución y los parámetros asociados proporciona una medida de incertidumbre a partir de la cual informar la construcción de un MPM (Tenhumberg et al., 2008). Además, el uso de la jerarquía en los modelos para estimar los valores faltantes y la fuerza de préstamo de otras poblaciones o especies pueden mejorar la estimación de parámetros (James et al., 2021; Tremblay & McCarthy, 2014).

Por último, los modelos poblacionales integrados representan un marco valioso para estimar indirectamente las tasas demográficas y la dinámica de la población (tamaño y estructura) mediante la combinación de fuentes de datos, en particular la combinación de datos individuales longitudinales con datos de censos poblacionales (Plard et al., 2019; Schaub & Kéry, 2021). Los modelos de población integrados permiten la construcción de modelos de población (incluyendo los MPM) mediante, (1) la combinación de diversas fuentes de datos, (2) la definición de una historia de vida a priori (a menudo se trata de algún tipo de modelo de población estructurado por etapas) y (3) la cuantificación de la máxima probabilidad de las tasas demográficas codificadas en la historia de vida, y citando las fuentes de los datos. Los modelos de población integrados son particularmente útiles cuando se conoce la incertidumbre en torno a la adquisición de datos (por ejemplo, en estudios de captura-marcado-recaptura) (Riecke et al., 2019).

### 3.5 | Vector de población {.unnumbered}

Una estimación de la estructura de la población, clasificada por edad o etapa, es una pieza útil de información cuando está disponible, pero no siempre se cuenta con esta información. Tiene lógica utilizar la estructura actual de la población como punto de partida para las proyecciones de la viabilidad de la población a corto y largo plazo (Werner & Peacock, 2019). Además, el utilizar la población vector (es decir, abundancia y distribución de etapas) para las proyecciones ayuda para tener en cuenta los efectos de la dinámica transitoria, que mide la efecto de la estructura de población no estacionaria en tasas de crecimiento de “near term” poblaciones (Capdevila et al., 2020). Los vectores reportados de etapa o edad de la población reflejan dos componentes clave: la estructura de población real en el censo en el tiempo t y las opciones metodológicas. Este segundo componente es fundamental para representar con precisión la población estudiada.


A través del desarrollo y curación de COMPADRE y COMADRE, hemos notado dos fuentes de error que afectan la estimación de los vectores de población. El primer error es un sesgo de detección, donde los investigadores identifican ciertas etapas/edades con una mayor tasa de detección que las etapas más crípticas (por ejemplo, plantas adultas versus bancos de semillas). El segundo error es la apropiación indebida de los métodos utilizados para cuantificar las tasas demográficas como base para estimar la abundancia de etapa. Este segundo error proviene de un malentendido de la diferencia entre estimar tasas y estimar números. Para medir las tasas demográficas, durante un censo, los investigadores a veces aumentan el esfuerzo de muestreo de ciertas clases de etapa/edad en relación a otras. Este diferencia en el esfuerzo en relación a etapa/edad es particularmente común cuando las clases de etapas/edades tienen probabilidades de supervivencia cercanas a sus límites (es decir, 0 y 1). Por ejemplo, en la demografía de los árboles, normalmente solo hay unos pocos individuos muy grandes por área examinada. Por lo tanto, a menudo los investigadores complementan el tamaño de la muestra de esta categoría al muestrear fuera del área predefinida (Jones y Hubbell, 2006). Sin embargo, muchos métodos para la estimación de tasas demográficas no proporcionan ninguna información sobre números y estructura de la población. Las tablas de vida de cohortes, que siguen a una cohorte de individuos a medida que envejecen, son ciegos a la estructura de la población en la que se desarrolla la cohorte. De hecho, puede que no haya tal población (por ejemplo, toda la historia de demografía basado en el estudio de cohortes realizada en laboratorio, que se remonta a Pearl en la década de 1920 (Pearl et al., 1927). La estimación de tasas mediante la técnica de captura-marcar-recaptura a partir de datos longitudinales extrae toda su inferencia de los individuos marcados y en ningún momento hace referencia al número y la estructura de los no marcados. La literatura sobre métodos de captura-marcar-recaptura para la estimación de tasas reconoce que estimar el tamaño de la población es mucho más difícil que estimar las tasas (Lebreton et al., 1992) y requiere diferentes modelos de captura-marcar-recaptura (por ejemplo, la inclusión de la evaluación de la respuesta hacía las trampas (dispuesto / renuente) en la estimación de tasas vitales.  

### 3.6 | Omitir etapas de vida crípticas {.unnumbered}

La identificación y estimación de tasas vitales en etapas crípticas representa un reto en ecología de poblaciones. Se determinan las etapas crípticas como puntos a lo largo del ciclo de vida de un organismo que están, de una forma u otra, ocultos o se pasan por alto por ecologistas de poblaciones al construir modelos de población (Doak et al., 2002). Una etapa de la vida puede ser críptica porque es logísticamente difícil de observar, o, aunque si es observable, a su vez es indistinguible de otra etapa (Nguyen et al., 2019). En las plantas, etapas crípticas pueden surgir de los bancos de semillas, como en el caso de las orquídeas, donde las semillas son demasiado pequeñas para ser observadas e identificadas en el campo (Paniw et al., 2017) o algunas perennes herbáceas (por ejemplo, Astragulus scaphoides) donde períodos de latencia vegetativa permiten que los individuos permanezcan escondidos bajo tierra durante una o más temporadas de crecimiento (Gremer & Sala, 2013). Además, los animales pueden exhibir etapas crípticas al pasar por diapausa o retrasos en el desarrollo debido a condiciones ambientales adversas (p. ej. Aedes albopictus: Jia et al., 2016). Aves marinas pelágicas (albatros, petreles, pingüinos) a menudo pasan etapas pre-reproductivas en el mar, a veces de duraciones de muchos años, y al ser así, se mantienen completamente crípticas hasta volver a la colonia reproductora como adultos. Métodos sofisticados de marcado-recaptura multi-estado pueden proporcionar estimaciones de parámetros para estas partes del ciclo de vida (p. ej., Jenouvrier et al. (2018), usando el algoritmo de eventos múltiples de Choquet et al. (2009)). Omitir una etapa críptica de la vida puede reducir la realismo biológico de un MPM y alterar el número de etapas en el MPM, que, en su conjunto puede impactar aún más los resultados demográficos (Salguero-Gómez y Plotkin, 2010; Tenhumberg et al., 2009). En algunos casos, las etapas de la vida crípticas solo se identificarán a través de un enfoque multidisciplinario. incluyendo métodos de campo y de laboratorio, junto con marcos bayesianos para integrar datos y conocimientos previos (por ejemplo, Paniw et al., 2017).


### 3.7 | Modelos de uno versus dos sexos  {.unnumbered} 


Gran parte de la demografía se centra en las mujeres, bajo los supuestos que la fertilidad está determinada por las hembras sin limitación por los machos (ver Caswell, 2001, p. 568). Dichos modelos pueden incluir machos (por ejemplo, Hunter et al., 2010), pero si la reproducción está determinada por las tasas femeninas (es decir, dominado por la etapa de hembras). Los machos representan un conjunto de etapas que no contribuyen al crecimiento de la población. La mayoría de los MPM de animales existentes están a base de hembras y femenino dominante (Salguero-Gómez et al., 2016) dados sesgos de muestreo hacia mamíferos y aves (Conde et al., 2019), a menudo no es factible, o necesario para la pregunta de investigación, rastrear interacciones reproductivas masculinas (Archer et al., 2022). Estos estudios, por lo general, asumen una proporción de sexos 1:1, y las tasas vitales son congruente por sexo y la reproducción no es limitada por los machos de la especie (Compagnoni et al., 2017; Miller & Compagnoni, 2022). Mientras que un sexo los modelos son comunes en animales MPM'S (actualmente 77% en Comadre v. 4.21.8), se debe tener cuidado no hacer suposiciones sobre la relación sexual dinámica dependiente dentro Estos sistemas (Archer et al., 2022).  De hecho, estos supuestos no pueden ser cumplido cuando cualquiera de los siguientes es cierto: que haya un sesgo en la proporción de sexos (Archer et al., 2022), hay  reprodución sesgadas (Sky et al., 2022), o un alta sensibilidad de la dinámica de la población en respuesta a la elección de apareamiento (Veran y Beissinger, 2009). Además, la detectabilidad de los diferentes sexos en el muestreo dependiente del sexo puede confundir más las estimaciones de la relación sexual y sus impactos asociados sobre las tarifas vitales si no se tiene en cuenta. Los modelos de dos sexos que no asumen la domininancia por un sexo no son lineales y requiere especificaciones de una función de apareamiento que describe la fertilidad en función del macho y la abundancia hembras (Caswell, 2001). La definición de tales funciones de apareamiento es generalmente difícil o imposible, excepto en casos especificos como la estricta monogamia (Jenouvrier et al., 2010). 

Informar sobre las proporciones de sexos puede expandir enormemente el alcance de un estudio (Shyu & Caswell, 2016a, 2016b); Por ejemplo, evaluar el impacto de la razón de sexo el efecto Allee (Boukal y Berec, 2002). Desafortunadamente, este tipo de analisis es raro y pocos ejemplos son notado en la bases de datos de COMPADRE y COMADRE. Además, si hay diferencias en los valores de la tasa vital entre sexos, como supervivencia, crecimiento y/o producción reproductiva en los modelos basado en un sexo solamente los MPM puede ometir procesos importantes (Archer et al., 2022; Caswell, 2001, p. 568). En plantas, ejemplos de investigaciones que incluye la dinámica de dos sexos raro (0.2% en COMPADRE v. 6.22.5). Este bajo porcentaje probablemente refleja en parte la rareza de la plantas dioecía u otros sistemas de apareamiento con dos o más sexos (Käfer et al., 2017) y los sistemas de apareamiento polígamos que hace que la reproducción y la dinamica poblacional limitado a los macho es raro (ver Compagnoni et al., 2017; Miller y Compagnoni, 2022).

### 3.8 | Irreductibilidad y ergodicidad  {.unnumbered}

Las propiedades de la irreductibilidad tiene implicaciones sobre la diversidad de eigenvalue de una matriz y, por lo tanto, interpretaciones biológicamente relevantes (e.g. tasas de crecimiento de la población, estructuras de etapa estable). Estas implicaciones son bien conocidos en la literatura sobre MPM (Caswell, 2001). Matriz que son irreducible son aquellas en la que el gráfico del ciclo de vida está completamente conectado; es decir, existe una ruta directa o indirecta desde cualquier etapa a cualquier otra etapa. A veces se afirma que los MPM reducibles son de alguna manera inválido; ellos no son inválido. Hay (al menos) cuatro situaciones en que matrices reducibles ocurren naturalmente.

1. Ciclos de vida con etapas post-reproductiva. Las etapas post-reproductiva no pueden contribuir a la potencialmente reproductiva (por ejemplo, MPM's para humanos, *Orcas*).
2. Modelos de dos sexos dominado por un sexo (generalmente mujeres, pero podría ser hombre). En un modelo dominado por hembras, toda la reproducción es acreditado a las mujeres. Los machos son producidos por las hembras, pero los machos no hacen contribución a la parte femenina del ciclo de vida (por ejemplo, Hunter et al. (2010) para osos polares).
3. Modelos espaciales en los que la dispersión es un direccional, como en los sistemas fluviales (ríos) o corrientes oceánicas.
4. En los modelos de Edad × etapas  (Caswell, 2009; Caswell y Salguero-Gómez, 2013). En estos modelos, la reproducción produce (por definición) individuos en la clase de edad 1, pero el modelo incluye todo combinaciones de edad y etapa, incluidas combinaciones imposibles de edad de clase 1 y etapas que no existen a los 1 años.

La reductibilidad puede o no ser fácil de detectar desde el gráfico del ciclo de vida, pero se puede evaluar numéricamente. La matriz **A** es irreducible si y solo si la matriz $\left(I+A\right)^{s-1}$ es positiva (Caswell, 2001). La irreductibilidad, junto con la primitividad, es una condición suficiente para Ergodicidad, garantizando que la población convergerá a la misma estructura estable independientemente de la condición inicial. Un matrix reducible puede no tener esta propiedad; claramente, por ejemplo, si una población comenzó con un solo individuo post-reproductivo no convergerán a la misma estructura que uno comenzó con algunos pre-reproductivos individuos. Con respecto a la ergodicidad, también se sabe que un MPM es ergódico si y solo si todas las entradas de su vector propio dominante izquierdo (v) son positivos (Stott et al., 2010). En resumen, a pesar del modelo apropiado estructura y parametrización correcta, los datos demográficos pueden conducir a matrices reducibles y/o no ergódico.


### 4 | Representación completa de un MPM en publicaciones {.unnumbered}

En esta sección, justificamos la necesidad de una presentación clara de MPM's en la literatura científica, sugerencias dónde archivar los MPM's en base da datos de acceso abierto, y discutir cómo estas dos acciones benefician a los autores, revista editorial, lectores, demógrafos comparativos, metaanalistas y la disciplina en general. Una tabla que contiene la lista de los datos a incluir al publicar MPM's junto con una justificación para la inclusión. Se pueden encontrar ejemplos de buenas prácticas en Tabla S1.

### 4.1 Partición de los procesos demográficos {.unnumbered}

Es importante definir a que se refiere cada elemento de una matriz de un MPM's. Varios procesos demográficos pueden superponerse al
mismo elemento matriz en un MPM, particularmente en especies con un rápido y/o variable ciclo de vida relativo a los intervalos de proyección del MPM. Por ejemplo, el parametro en un MPM que representa el enlace entre individuos grandes en el tiempo **t** y individuos más pequeños en el tiempo **t+1** podría corresponder a la reproducción sexual, reproducción clonal, fisión, retroceso o un cojunto de los procesos anteriores. Las derivaciones matemáticas de parametros clave de la historia de vida (por ejemplo, generación el tiempo, la esperanza de vida, la tasa de senescencia, el grado de iteroparidad) requieren que estos procesos están claramente separados (Jones et al., 2022). Esto separaciones es crítica para la familia de análisis basados en las cadenas de Markov; la matriz U define las transiciones de estado transitorio en un analisis de Chain de Markov absorbente (Caswell, 2011, 2013). Claramente describiendo la estructura subyacente de las tasas demográficas en un diagrama del ciclo de vida y su consecuente modelo de población de la matriz completa **A**, se puede separar matrices en los procesos de supervivencia (por ejemplo, progresión/crecimiento, retroceso/ contracción, fisión, fusión, estasis) en la submatriz **U**, una matriz de reproducción sexual en el submatriz **F** y la reproducción clonal en la submatriz **C** (Figura 4). Es importante destacar que tanto que las matrices de **F** y **C** incluye elementos que deben incorporar la supervivencia de acuerdo con el tipo de censo (es decir,pre-/post-reproductivo censo).

Informar claramente la matriz **A** y las submatrices **U**, **F** y **C** se lleva dos beneficios clave: (1) indica explícitamente cómo se generan los valores en **A** de tasas vitales subyacentes; y (2) los submatrices pueden ser utiliza para calcular una gran gran cantidad de medidas demográficas que no pueden
calcularse a partir de solamente la matriz **A**, como la longevidad (promedio y varianza), tiempos de ocupación (promedio y variaciones), la distribución de la reproductiva de por vida de los individuos (promedio y variaciones), taza de reproducción neta, tiempo de generación y entropía (KeyFitz Entropy (KeyFitz, 1968) y la entropía de Demetrius (Demetrius, 1992)) entre otros.


### 4.2 Atribución de fuentes de datos secundarias {.unnumbered}

Las fuentes de datos secundarias son críticas para la reproducibilidad. Las fuentes de datos proporcionan información y soporte para las metodologías utilizadas en la construcción MPM. En algunos casos, los MPM simplemente usan datos secundarios para estimar algunos parametros del ciclo de vida, mientras que otros se construyen puramente de fuentes secundarias (ver Tabla S1). Las fuentes secundarias incluyen estudios previos, datos de bases de datos, simulaciones, observaciones indirectas y estimaciones teóricas. El uso de fuentes de datos secundarias puede significar que el MPM final no representa con precisión las tasas de razon vitales, y así debe reconocerse en la sección de métodos de la publicación o su información de apoyo. La comunicación de fuentes secundarias deberia ser suficiente para determinar su provenencia e incluye la fuente de los datos, si se estimó un punto, el intervalo de confianza o la distribución
y como se integró con la fuente de datos primaria, así como la justificación de su inclusión. Por ejemplo, Omeyer et al. (2021) presenta una tabla de fuentes de datos utilizadas en la construcción de MPM. Si estas feuntes secundarias no se reconocen en conjunto con el MPM, los inferidos procesos demográficos, por realista que sean, pueden no pasar revisión por pares ni aceptada de la comunidad científica. A su vez, la comunicación clara de estas fuentes secundarias es muy recomendable.

### 4.3 Archivando los datos en COMPADRE y COMADRE {.unnumbered}

Proponemos que las bases de datos de la matriz de COMPADRE y COMADRE proporcione la forma más adecuada de archivar y acceder a MPM's. Mientras reconocemos que hay otros repositorios de bases de datos ecológicas (por ejemplo, Dryad: <<https://datadryad.org/>>; figshare: <<https://figshare.com>>; Zenodo: <<https://zenodo.org>>), la base de datos de COMPADRE COMADRE de acceso abierto (<<https://compadre-db.org/Contribute>>) proporciona una plataforma de archivo de datos dedicada, específicamente para MPM's, que permite contribuciones directas de los investigadores y la digitalización de MPM publicados por nuestros equipos de validación de datos. La integración de un portal usando una pagina web para la entrada de datos proporciona un proceso de curación de datos estructurado (es decir, desde la detección, la estandarización, hasta la validación) que pueden acomodar MPM de diferentes dimensiones y diversas historias de vida. Al ingresar, los MPM se complementan con variables biogeográfico relevante y detalles sobre la metodología del censo en COMPADRE y COMADRE. Detalles de la publicación original, incluyendo **doi** y
Funcionalidad de citas (ver <<https://compadre-db.org/Education/article/obtaining-references>> se almacenan junto con cada MPM para garantizar que su contribución a cualquier publicación futura es reconocida. Todos los datos están archivados a largo plazo a través de Oxford Open Access y con apoyo de la Biblioteca Bodleian.

Mejoras recientes para COMPADRE y COMADRE Ayudará aún más a la comunidad de cientifica. Anteriormente, las bases de datos solo eran accesibles a través de la descarga de un archivo **R-Object** que contenía todas las matrices en esa versión de la base de datos. La base de datos es ahora accesible a través de un sitio web (<<https://compadre-db.org/QueryDatabase>>) que permite a los usuarios encontrar y descargar matrices individuales. También nos esforzamos por empoderar a los investigadores y educadores. con materiales de enseñanza (<<https://compadre-db.org/Education>>) y la producción de nuevos paquetes R (Jones et al., 2022) para facilitar escalabilidad de MPM investigación. Junto con estos materiales, todos los detalles de la estructura de la base de datos y el flujo de trabajo son de acceso libre (<<https://jonesor.github.io/CompadreGuides/user-guide.html>>). Estas mejoras en las bases de datos y su estructura de interfaz ha sido directamente dirigido a equipar a los demógrafos con más herramientas para realizar investigaciones y capacitar a los estudiantes en MPM's junto con el aumento en
transparencia de la base de datos para garantizar las mejores prácticas en la investigación.
