---
title: "Dinamica Poblacional"
#output:
#  bookdown::gitbook:
#    highlight: tango
    #code_folding: hide
author: 
 - name: Raymond L. Tremblay 
   affiliation: Universidad de Puerto Rico, Recinto de Río Piedras y Humacao, Departamento de Biología, San Juan, Puerto Rico
 - name: Aucencia Emeterio Lara
   affiliation: Colegio de la Frontera Sur, ECOSUR, México
 - name: Elaine González
   affiliation: Orquídeario Soroa, Universidad de Pinar del Río, Apdo. postal No. 5 Candelaria, Pinar del Río, Cuba
 - name: Mariana Hernández-Apolinar
   affiliation: Universidad Nacional Autónoma de México, Facultad de Ciencias, México
 - name: Fabiola Hernández
   affiliation: Colegio de la Frontera Sur, ECOSUR, México
 - name: Diana C. Molina Ozuma
   affiliation: Colegio de la Frontera Sur, ECOSUR, México
 - name: Demetria Mondragón
   affiliation: Centro Interdisciplinario para la Investigación Integral Regional, CIIDIR-Oaxaca, México
 - name: Ernesto Mujíca Benitez
   affiliation: Orquídeario Soroa, Universidad de Pinar del Río, Apdo. postal No. 5 Candelaria, Pinar del Río, Cuba
 - name: Paola Portillo Tzompa
   affiliation: Universidad Nacional Autónoma de México, Facultad de Ciencias, México
 - name: Roberto Salguero Gómez
   affiliation: Laboratory of Evolutionary Biodemography Laboratory, Max Planck Institute for Demographic Research, Konrad-Zuse-Straße 1, Rostock DE-18057, Germany; ARC Centre of Excellence for Environmental Decisions, School of Biological Sciences, The University of Queensland, Goddard building 8, St. Lucia, Qld 4072, Australia;
 - name: Adriana Ramírez Martínez
   affiliation: Centro Interdisciplinario para la Investigación Integral Regional, CIIDIR-Oaxaca, México
 - name: Tamara Ticktin
   affiliation: Department of Botany, University of Hawaii at Manoa, 3190 Maile Way, Honolulu, HI 96822, USA.
   
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
# biblio-style: apalike. # only applies to pdf format

description: |
  Este libro digital es una introdución al estudio de la Dinámica Poblacional con ejemplos de orquídeas. Los capítulos estan organizado de lo más básico a más complejo en la recolección de datos, análisis y interpretación de los resultados. Incluyendo acercamientos que fueron desarrollados más reciente para el análisis de datos de dinámica poblacional. Los capitulos de **Métodos Bayesiano de calcular las transiciones y fecundidad** y **Un protocolo para informar sobre modelos discreto de estructura de población** son especialmente importante para reducir los errores de cálculos de los parámetros y divulgación de los trabajos. El capitulo de **Impacto de datos sin sentidos** es *PRIMORDIAL* para los investigadores que trabajan con datos de dinámica poblacional y debería ser un capitulo donde uno regrese continuamente para evaluar sus análisis y interpretaciones. En otra palabra si los datos no tiene sentido biológico y matemático los resultados no sirven.  En adición se presenta múltiples ejemplos de datos sin sentido y como estos datos pueden impactar los resultados de los análisis de forma negativa.
  
Fecha de actualización: 2024-09-30

link-citations: yes

editor_options: 
  markdown: 
    wrap: 72 
---









*******



# Dinámica Poblacional

El estudio de la Dinámica Poblacional tiene como objetivo desarrollar conocimiento sobre los patrones y procesos intra-específica y variables inter-específicos que impacta el crecimiento de una especies en particular.  Tradicionalmente muchos de los trabajos de dinámica poblacional se enfocan en los estudios intra-específica, fomentando una perspectiva que las especies no inter-actúan con su ambiente abiótico o las especies en su entorno ecológico. Como toda las áreas de la ecología el desarrollo de los conceptos tienden a ser simplista al principio y con el tiempo se van complicando de forma conceptual y metodológicos. Para entender los procesos dinámicos de cualquier especie cuando se comienza a estudiar uno debería comenzar por modelos simples y con el tiempo ir complicando los modelos para entender los procesos más complejos y evaluar si realmente complicando los modelos se puede explicar mejor los procesos y patrones.  Este libro comienza por explicar las herramientas, conceptos y métodos más básicos en la dinámica poblacional enfatizando los supuestos y la limitaciones en el uso de cada indices y sus acercamientos. Al final del libro se enfatiza múltiples puntos que el investigador debería considerar al momento de hacer un análisis de dinámica poblacional y para reducir los sesgos y errores en los análisis. 

## Objetivo del libro: 

Este libro es orientado a dos grupos de personas: Para los estudiantes de pre-grado y posgrado que están interesados en aprender sobre la dinámica poblacional y para los investigadores que desean tener una guía de los conceptos y métodos tradicionales y más recientes en la dinámica poblacional. Pero nota que este libro no es un libro de texto tradicional, es una guía práctica de los conceptos y métodos en la dinámica poblacional. En cada capítulo se presentará una introducción a los conceptos y métodos y ejemplos prácticos de como aplicar estos conceptos y métodos usando la matemática más básica y como se interpreta de forma biológica.  En cada caso se ampliará con métodos y funciones disponible en varios paquetes de **R** para facilitar el análisis. La gran mayoría de los ejemplos matemáticos básicos se presentarán en **R**, y algunos en **MS Excel**.  Al final se debería tener una apreciación de la diversidad de metodologías y conceptos en la dinámica poblacional y como se puede aplicar a su estudio para contestar varios tipos de preguntas ecología, de conservación y evolución.Un esfuerzo de recopilar referencias de la literatura de la dinámica poblacional de las orquídeas y otros organismos (tanto animales como otro grupos de plantas) se ha hecho para que el lector pueda tener una idea de los estudios que se han hecho. Se espera que la diversidad de ejemplos puede dar una apreciación holística de la diversidad de acercamiento, fortalezas y retos.


## Estructura del libro

El libro se divide en **xx** capítulos. Estos capítulos están organizados para que el lector pueda seguir el proceso de recolección de datos, análisis y interpretación de los resultados. Incluyendo acercamientos que fueron desarrollados más reciente para el análisis de datos de dinámica poblacional. Los capítulos de **Métodos Bayesiano de calcular las transiciones y fecundidad** y **Un protocolo para informar sobre modelos discreto de estructura de población** son especialmente importante para reducir los errores de cálculos de los parámetros y divulgación de los trabajos. 

1. **Ciclo de vida de una especie**:

El primer capitulo presenta un concepto fundamental en la dinámica poblacional, el ciclo de vida. Cada especie tiene un ciclo de vida **REAL**, donde el investigador siempre debería tratar de replicar en la recolección de datos incluyendo información para cada etapa/edad de la vida de la especie. El ciclo de vida **REAL** es la base para entender los procesos de la dinámica poblacional. Noto aquí que entre el ciclo de vida **REAL** de una especie y la capacidad de recolección de datos sobre el mismo hay una brecha que el investigador debería tratar de cerrar. Un ejemplo extremo, recientemente acaban de descubrir un cadáver de una especies de ballena en Nueva Zelanda, que se llama "Spade tooth whale" donde se ha encontrado desde su descripción (1874) solamente 6 individuos. Sin duda hacer un estudio considerando el ciclo de vida de esta especie sería un reto. Cualquier especie que se estudie con tan pocos datos es un reto, y múltiples supuestos del ciclo de vida de la especie tendrían que ser incluidos.  Lo más importante es reconocer lo que es un supuesto (y por consecuencia una hipótesis) y lo que es un hecho o sea la realidad. 

En las orquídeas, hay multiples etapas del ciclo de vida, las etapas de semillas, germinación (colonización de semillas por un hongo apropiado para su germinación en el campo) y plántulas son etapas críticas en el ciclo de vida de la especie, pero son etapas que son difíciles de recolectar datos en el campo. Estas etapas son primordial para entender la dinámica poblacional de las orquídeas, pero desafortunado estamos todavía muy ignorante de estas etapas en el campo, y la variación en los procesos y patrones. Enfatizo el hecho que son procesos en el hábitat natural, mucho de lo que conocemos es de estudios en laboratorio, que pudiese ser procesos y patrones sesgados. 

Lo importante de este capitulo es reconocer varios aspectos del ciclo de vida de una especie y como se puede categorizar de forma practica para la recolección de datos para entender los procesos de la dinámica poblacional y reconocer los supuestos y limitaciones en la interpretaciones de lo que es el ciclo de vida de las orquídeas recolectado versus lo ciclos de vida real de una especie.

2. **Recolección de datos**:

Ese capitulo se enfoca en la recolección de datos en el campo, métodos de muestreo, marcar, identificar y seguir los individuos a través de múltiples periodos de tiempo. Enfatizamos tres tipos de recolección de datos basado en su ciclo de vida, epifitas, terrestres, y terrestres con latencia. Para ayudar en la compresión de los métodos de muestreo se presentará ejemplos de la literatura o experiencia de los autores. En adición se presenta múltiples métodos para hacer estudios de marca y recaptura en orquídeas y se sugiere múltiples sistema de marca para reducir los errores de confusión en identificar individuos entre poblaciones y periodo de muestreo.

3. **Transiciones de etapa/edad**:

El tercer capitulo se enfoca en como calcular las transiciones de una etapa/edad de un muestreo a otro. Se comienza con análisis que se puede hacer a mano, y después se presentará como hacerlo en R.  En este capitulo se presenta los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Estos métodos tradicional son especialmente practico para poblaciones grandes con tamaño de muestra grande para cada una de las etapas o grupo de edad. Cuando los tamaños de muestra son pequeñas o la probabilidad de una transición es rara vea el capitulo de métodos Bayesianos para calcular las transiciones.

4. **Calcular la fecundidad**:

Este capitulo se enfoca en como calcular la fecundidad de una especie. El capítulo se enfoca en tratar de que los investigadores reconozcan que los indices de fecundidad tienen que estar relacionados con las etapas de vida de la especie que se esta modelando. En otra palabra si la primera etapa del ciclo de vida son plántulas, la fecundidad debería ser relacionada con la producción de semillas que se convierte en plántulas. En este capitulo se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. En adición se asume en estos calculo tradicional que las probabilidad de fecundidad tienen una distribución normal, y suficiente grandes.  Si las probabilidades de fecundidades son raras y los parámetros son cerca de cero vea el capitulo de métodos Bayesianos para calcular la fecundidad. En adición si la distribución de fecundidad no cumple con una distribución normal vea el capitulo de métodos Bayesianos para calcular la fecundidad. Es posible que una distribución gamma sea una mejor acercamiento a la distribución de fecundidad de una especie.


5. **Relación entre las matriz de transiciones, fecundidad y clonaje**:

Este capítulo se enfoca en como relacionar las diferentes matrices de transiciones, fecundidad y clonaje.  La suma de los tres tipo de matriz refleje el ciclo de vida de la especie estudiado. Separar las matriz en una de transición, fecundidad y clonaje ayuda a aclarar los procesos y patrones de la dinámica poblacional en adición que ciertos indices depende que la matriz sea separada. Por ejemplo para calcular el largo de vida de una especies (life span) se usa solamente la matriz de transición y o clonaje [@orive1993effective].

6. **Métodos Bayesiano de calcular las transiciones y fecundidad**:

Este nuevo procedimiento incluido en un paquete de R, llamado **raretrans** tiene como objetivo resolver múltiples asuntos en la estimación de los parámetros de transiciones y fecundidad. Específicamente en la falta de datos de transiciones raras y datos con parámetros sin sentido biológicos (ejemplo: supervivencia perfecta, ninguna mortandad). Aunque este paquete es nuevo y no ha sido implementado en múltiples estudios todavía, se espera que las funciones en este paquete sean herramientas útiles para los investigadores que trabajan con datos de dinámica poblacional especialmente cuando se trata de especies raras donde la recolección de datos es limitada a tamaño de muestras pequeñas [@tremblay2021population; @ospina2023effect].


7. **Crecimiento poblacional**:

El crecimiento poblacional se refiere a si la población es estable, creciendo o reduciendo. Se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Se discute los diferentes tipos de indices de crecimiento poblacional y como se puede interpreta.

8. **Análisis de sensibilidad y elasticidad**:

Los análisis de sensibilidad y elasticidad son herramientas para evaluar la importancia relativa de los cambios en los parámetros de la matriz de transición sobre el crecimiento poblacional. En este capitulo se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Se discute cual es la diferencias entre matriz de sensibilidad y elasticidad y como se puede interpretar los resultados como herramienta para el manejo de las especies para su conservación. Un ejemplo de la importancia de estos análisis se encuentra en los trabajos sobre la tortuga boba, *Caretta caretta* [@crouse1987stage; @crowder1994predicting] donde se ha encontrado que la supervivencia de las hembras adultas es el parámetro más importante para el crecimiento poblacional de la especie, mucho más que la supervivencia de los huevos (eso no quiere decir que uno no debería proteger los huevos). Lo que identifica es que para cada adulto que se protege tiene un potencial de aumento poblacional muchos más grande que salvar un huevo. 


9. **Indices de historia de vida**:

10. **Dinámica de transiciones**:

La dinámica de transciones evalúa los cambios en parámetros (tamaño poblacional, supervivencia, fecundidad) a lo largo del tiempo o a tiempo corto o largo. Ejemplos, incluye como la distribuciones de etapas al comienzo del estudio impacta el crecimiento poblacional, o como la supervivencia de una etapa impacta el crecimiento poblacional. En este capitulo se presentará los métodos de calcular de forma simple y se discute algunos los supuestos y limitaciones. Gran parte de estos acercamiento fuero desarollados por Stott y collegas [@stott2010boom; @mcdonald2016transients] y otros [@heggerud2023transient] han usado en múltiples estudios de dinámica poblacional evaluando como los cambios de transiciones son dinámicos.  La ventaja de esta acercamiento es que se puede evaluar los cambios en los parámetros de la matriz de transición y como impacta el crecimiento poblacional y no asumir que los cambios necesariamente lleguen a una población de son estables.

11. **Funciones de transferencias**:

12. **Experimento de Respuesta de Tabla de Vida**:

13. **Variación Espacial y Temporal: simulaciones**:

14. **Impacto de datos sin sentidos**:

Este capitulo es *PRIMORDIAL* para los investigadores que trabajan con datos de dinámica poblacional y debería ser capitulo donde uno regrese continuamente para evaluar sus análisis y interpretaciones. Hay un dicho en Ingles que dice, *Garbage in Garbage out*. En otra palabra si los datos no tiene sentido biológico y matemático los resultados no sirven, .  En este capitulo se presentará múltiples ejemplos de datos sin sentido y como estos datos pueden impactar los resultados de los análisis de forma negativa. 

15. **Un protocolo para informar sobre modelos discreto de estructura de población**:

En este capitulo se presenta un protocolo para informar sobre modelos discreto de estructura de población. Este protocolo es una guía para los investigadores para asegurar que toda la información necesaria es presente para evaluar críticamente sus manuscritos. Este capitulo es una traducción de **A standard protocol to report discrete stage-structured demographic information** [@gascoigne2023standard]. *Antes de publicar un estudio usando matrices de proyección se debería asegurar que cumple con la mayoría de las recomendaciones presentadas en este protocolo.*

16. **Estudios evolutivos de la dinámica poblacional: Ejemplos con Orquídeas**:

17. **Sinopsis Históricos de Estudios de Dinámica Poblacional en Orquidea**:

18. **COMPADRE: Una base de datos de matrices de vida de plantas**:

Todos las publicaciones (revido por pares, tesis, informes técnicos) que tienen matrices de vida de plantas están incluido en COMPADRE (por lo menos es el objetivo). En este capitulo se presenta la base de datos con un sub-grupo de especies (las Orquídeas) y se evalúa como utilizar la base datos. La funciones (scripts) para extraer las matrices y analizar los datos están disponible en el paquete de R **RCompadre**. En adición se evalúa múltiples hipótesis sobre la dinámica poblacional de las orquídeas y determinar si hay patrones generales en la dinámica poblacional de las orquídeas entre grupos (por ejemplo terrestres vs. epífitas, distribución mundial, tiempo de estudios, etc). Este un capitulo para dar ideas a investigadores que trabajan con datos de dinámica poblacional y como se puede hacer análisis de datos a gran escala. 

19. **Conclusiones**:

En este capitulo se presentará las conclusiones generales del libro y se presentará las recomendaciones para futuras investigaciones en la dinámica poblacional. En adición se hace referencias a nuevos métodos y conceptos que no se han presentado en el libro.

Apéndice 1: **Lista de especies de Orquídeas estudiadas usando PPM**:

Lista de las especies de orquídeas que se han estudiado en la dinámica poblacional y la referencia de los estudios. EL tema principal de cada manuscrito/estudio esta presentado en una tabla para que el lector pueda buscar los estudios que le interesa.




## Paquetes de R principales usado en el libro

Los paquetes principales para el análisis de dinámica poblacional al incluye

 - *popbio*: un paquete para analizar datos de dinámica poblacional basado en funciones que se encuentran en el libro de Caswell [@caswell2001matrix] y en el libro de Morris y Doak [@morris2002quantitative] por edades o etapas [@popbio2007].
 
 - *popdemo*: un paquete que incluye Herramientas para modelar poblaciones y demografía utilizando modelos de proyección matricial, con implementaciones de modelos deterministas y estocásticos. Incluye proyección de población, índices de tamaño y crecimiento de la población a corto y largo plazo, análisis de perturbaciones, convergencia hacia la estabilidad o estacionaria [@popdemo2021].
 
 - *raretrans*: Funciones para crear modelos matriciales de población a partir de una combinación de datos sobre transiciones de etapa/edad con información previa bayesiana. Esto compensa los problemas estructurales causados por la falta de observaciones de transiciones raras y datos sin sentido biológicos [@raretrans2024] (vea capitulo XX).
 
 - *Rage*: Funciones para calcular métricas de historia de vida utilizando modelos matriciales de población ("MPM"). Descrito en Jones [@Rage2022]. 
 
 - *RCompadre*: Un paquete para analizar datos recopilado en la base de datos de COM(P)ADRE: ese es un base de datos de matrices de vida de plantas y animales usando matrices [@jones2022rcompadre].
 

Otros paquetes que se usan para analizar datos, mayormente para manipular datos, hacer modelos estadísticos y visualización incluye:

 - *ggplot2*: # para hacer gráficos 
 - *dplyr*: # para manipular datos
 - *tidyr* # para manipular datos
 - *lubridate* # para trabajar con fechas

 


## Libro digital y archivos de datos
 
El libro se encuentra en el siguiente enlace, donde el acceso a todas las funciones y datos están disponibles para reproducir los ejemplos utilizado en el libro. 

https://raymondltremblay.github.io/Diagnostico_Poblacional/
 
 
 

 Revisión: Sept 14, 2024